---
name: CI Test

"on":
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      runner:
        description: Select runner OS
        required: true
        default: ubuntu-latest
        type: choice
        options:
          - ubuntu-latest
          - ubuntu-22.04

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    outputs:
      os: ${{ steps.check_event.outputs.os }}
    steps:
      - name: Determine runner OS
        id: check_event
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "os=${{ github.event.inputs.runner }}" >> $GITHUB_OUTPUT
          else
            echo 'os=ubuntu-latest' >> $GITHUB_OUTPUT
          fi
      - name: Set up job
        run: echo "Setting up job on ${{ steps.check_event.outputs.os }}"

  build-and-screenshots:
    name: Build and Take Screenshots
    needs: check
    runs-on: ${{ needs.check.outputs.os }}
    steps:
      - uses: actions/checkout@v4.1.7  # Updated to latest stable version with commit pinning recommended
        with:
          # Limit git history depth for security and performance
          fetch-depth: 1

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
